name: Next.js CI

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:

      NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyBtWgQD80yFjPzSWZEdzoX8hiG6AjPozJ8
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=cineverse-a9a05.firebaseapp.com
      NEXT_PUBLIC_FIREBASE_PROJECT_ID=cineverse-a9a05
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=cineverse-a9a05.firebasestorage.app
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=448334753349
      NEXT_PUBLIC_FIREBASE_APP_ID=1:448334753349:web:ac199cabcce33bb060fd2c
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-0Z9K6X1J3H

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

        with:
          node-version: 22

      - run: npm install

      - run: npm run build